/// Generated by AssetsRefGenerator on 2022/04/20
class Res {
  static const String account_created_bg =
      "assets/images/account_created_bg.png";
  static const String leftArrow = "assets/images/left_arrow.png";
  static const String protocol = "assets/images/protocol.png";
  static const String trackingCar = "assets/images/tracking_car.png";
  static const String pendingApproval = "assets/images/pending_approval.png";
  static const String connected = "assets/images/connected.jpg";
  static const String myProfile = "assets/images/my_profile.png";
  static const String driverList = "assets/images/driver_list.png";
  static const String billFlow = "assets/images/bill_flow.jpg";
  static const String trackVehicle = "assets/images/track_vehicle.png";
  static const String vehicleDetails = "assets/images/vehicle_details.png";
  static const String bankDetails = "assets/images/bank_details.png";
  static const String transactionHistory = "assets/images/transaction_history.png";
  static const String withdrawHistory = "assets/images/withdraw_history.png";
  static const String totalEarning = "assets/images/total_earning.png";
  static const String management = "assets/images/management.png";
  static const String privacy = "assets/images/privacy.png";
  static const String termsAndConditions = "assets/images/terms_and_conditions.png";
  static const String logout = "assets/images/logout.png";
  static const String earningAd = "assets/images/earning_ad.jpg";

  static const String app_logo = "assets/images/app_logo.png";
  static const String app_name_logo = "assets/images/app_name_logo.png";
  static const String bill_icon_image = "assets/images/bill_icon_image.png";
  static const String points = "assets/images/points.png";
  static const String topUp = "assets/images/top_up.png";
  static const String sideBorder = "assets/images/side_border.png";
  static const String car1 = "assets/images/car1.png";
  static const String uploadImage = "assets/images/upload_image.png";

  static const String bringme_info_header =
      "assets/images/bringme_info_header.png";
  static const String cancel_order_header =
      "assets/images/cancel_order_header.png";
  static const String cancel_order_icon = "assets/images/cancel_order_icon.png";
  static const String cancelled = "assets/images/cancelled.png";
  static const String track = "assets/images/track.png";
  static const String logoutCar = "assets/images/logout_car.jpg";
  static const String vehicleRegister = "assets/images/vehicle_register.jpg";
  static const String cancelled_delivery_icon =
      "assets/images/cancelled_delivery_icon.png";
  static const String cart_icon = "assets/images/cart_icon.png";
  static const String completed_delivery_icon =
      "assets/images/completed_delivery_icon.png";
  static const String coupne_icon = "assets/images/coupne_icon.png";
  static const String delivered = "assets/images/delivered.png";
  static const String delivery_tutorial_bg =
      "assets/images/delivery_tutorial_bg.png";
  static const String delivery_tutorial_bg_2 =
      "assets/images/delivery_tutorial_bg-2.png";
  static const String download_icon = "assets/images/download_icon.png";
  static const String driver_instruction_icon =
      "assets/images/driver_instruction_icon.png";
  static const String edit_icon = "assets/images/edit_icon.png";
  static const String ellipse_from = "assets/images/ellipse_from.png";
  static const String ellipse_to = "assets/images/ellipse_to.png";
  static const String euclid_circular_a_bold =
      "assets/fonts/euclid_circular_a_bold.ttf";
  static const String euclid_circular_a_light =
      "assets/fonts/euclid_circular_a_light.ttf";
  static const String euclid_circular_a_medium =
      "assets/fonts/euclid_circular_a_medium.ttf";
  static const String euclid_circular_a_regular =
      "assets/fonts/euclid_circular_a_regular.ttf";
  static const String euclid_circular_a_semibold =
      "assets/fonts/euclid_circular_a_semibold.ttf";
  static const String forgot_password_header =
      "assets/images/forgot_password_header.png";
  static const String line_gredient = "assets/images/line_gredient.png";
  static const String location = "assets/images/location.png";
  static const String location_transperant =
      "assets/images/location_transperant.png";
  static const String login_header = "assets/images/login_header.png";
  static const String near_by_store_header =
      "assets/images/near_by_store_header.png";
  static const String nearby_store_icon = "assets/images/nearby_store_icon.png";
  static const String notification_icon = "assets/images/notification_icon.png";
  static const String notification_icon1 =
      "assets/images/notification_icon1.png";
  static const String order_delivered_header =
      "assets/images/order_delivered_header.png";
  static const String order_header_icon = "assets/images/order_header_icon.png";
  static const String order_info_header = "assets/images/order_info_header.png";
  static const String order_tutorial_2 = "assets/images/order_tutorial-2.png";
  static const String order_tutorial_bg = "assets/images/order_tutorial_bg.png";
  static const String payment_icon = "assets/images/payment_icon.png";
  static const String product1 = "assets/images/product1.png";
  static const String product2 = "assets/images/product2.png";
  static const String product_detail_img =
      "assets/images/product_detail_img.png";
  static const String report_icon = "assets/images/report_icon.png";
  static const String reset_password_header =
      "assets/images/reset_password_header.png";
  static const String splash_bg = "assets/images/splash_bg.png";
  static const String store1 = "assets/images/store1.png";
  static const String store2 = "assets/images/store2.png";
  static const String store3 = "assets/images/store3.png";
  static const String bringMeIcon = "assets/images/bring_me_icon.png";
  static const String store_header = "assets/images/store_header.png";
  static const String store_icon = "assets/images/store_icon.png";
  static const String store_product = "assets/images/store_product.png";
  static const String store_product1 = "assets/images/store_product1.png";
  static const String tutorial1 = "assets/images/tutorial1.png";
  static const String tutorial2 = "assets/images/tutorial2.png";
  static const String uk_flag = "assets/images/uk_flag.png";
  static const String user_1 = "assets/images/user_1.png";
  static const String user_2 = "assets/images/user_2.png";
  static const String user_3 = "assets/images/user_3.png";
  static const String user_4 = "assets/images/user_4.png";
  static const String vehicle = "assets/images/vehicle.png";
  static const String bill = "assets/images/bill.png";
  static const String user = "assets/images/user.png";
  static const String logo = "assets/images/logo.png";
  static const String editPhoneNumber = "assets/images/edit_phone_number.png";
  static const String email = "assets/images/email.png";
  static const String phone = "assets/images/phone.png";
  static const String lock = "assets/images/lock.png";
  static const String bank = "assets/images/ic_bank.png";
  static const String truck = "assets/images/truck_fast.png";
  static const String wallet = "assets/images/wallet.png";
  static const String showPassword = "assets/images/show_password.png";
  static const String dateOfBirth = "assets/images/date_of_birth_icon.png";
  static const String flag = "assets/images/flag.png";
  static const String camara = "assets/images/camara.png";
  static const String purse = "assets/images/purse.png";
  static const String saved = "assets/images/saved.png";
  static const String details_icon = "assets/images/details_icon.png";
  static const String hidePassword = "assets/images/hide_password.png";
  static const String notification_bell = "assets/images/notification_bell.png";
  static const String selcted_check_box = "assets/images/selcted_check_box.png";
  static const String saudi_arabia_flag = "assets/images/saudi_arabia_flag.png";
  static const String selectedCheckbox = "assets/images/selected_checkbox.png";
  static const String attached = "assets/images/attached.png";
  static const String send = "assets/images/send.png";
  static const String voice = "assets/images/voice.png";
  static const String offline = "assets/images/oflfine.png";
  static const String bike = "assets/images/bike.png";
  static const String black_ace = "assets/images/black_ace.png";
  static const String car_black = "assets/images/car_black.png";
  static const String home = "assets/images/home.png";
  static const String delivery = "assets/images/delivery.png";
  static const String account = "assets/images/account.png";
  static const String accountSelected = "assets/images/account_selected.png";
  static const String gps = "assets/images/gps.png";
  static const String chat = "assets/images/chat.png";
  static const String online = "assets/images/online.png";
  static const String backArrowBlack = "assets/images/back_arrow_black.png";
  static const String backArrow = "assets/images/back_arrow.png";
  static const String bag = "assets/images/bag.png";
  static const String app_name = "assets/images/app_name.png";
  static const String from_store = "assets/images/from_store.png";
  static const String map_blue_pin = "assets/images/end_pick_up.png";
  static const String userLocation = "assets/images/user_location.png";

  //static const String endPickUp = "assets/images/end_pick_up.png";
  static const String left_arrow_icon = "assets/images/left_arrow_icon.png";
  static const String read_message = "assets/images/read_message.png";
  static const String chatSelected = "assets/images/chat_selected.png";
  static const String homeSelected = "assets/images/home_selected.png";
  static const String message_icon = "assets/images/message_icon.png";
  static const String start_pick_up = "assets/images/start_pick_up.png";
  static const String selected_delivery = "assets/images/selected_delivery.png";
  static const String blueCar = "assets/images/blue_car.png";
  static const String redAce = "assets/images/red_ace.png";

  static const String eicher = "assets/images/eicher.png";
  static const String copy = "assets/images/copy.png";
  static const String coins = "assets/images/coins.png";
  static const String refer = "assets/images/refer.jpg";
  static const String insuranceImage = "assets/images/insurance_image.png";
  static const String checkList = "assets/images/checkList.png";
  static const String tickCircle = "assets/images/tick-circle.png";
  static const String change_password_sucess =
      "assets/images/change_password_sucess.png";
  static const String unselecedCheckbox =
      "assets/images/unseleced_checkbox.png";
  static const String orderSccessfully = "assets/images/order_sccessfully.png";
  static const String accountSuccessfully =
      "assets/images/account_successfully.jpg";

  static const String vendorRequest = "assets/images/vendor_request.png";
  static const String currentLocationPin =
      "assets/images/current_location_pin.png";
  static const String destinationPin = "assets/images/destination_pin.png";
  static const String addLicense = "assets/images/add_license.png";
  static const String complaintFrontImage =
      "assets/images/complaint_front_image.jpg"




  ;
}
